AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planning-poker

  SAM Template for planning-poker API Gateway and Lambdas

Globals:
  Function:
    Timeout: 3

Resources:
  PlanningPokerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PlanningPokerTable
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  PlanningPokerVote:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PlanningPokerVote
      AttributeDefinitions:
        - AttributeName: voteId
          AttributeType: S
      KeySchema:
        - AttributeName: voteId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  PlanningPokerWebsocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: PlanningPokerWebsocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ApiGatewayEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/apiGatewayEvents/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlanningPokerTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PlanningPokerVote
        - Statement:
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource:
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PlanningPokerWebsocketApi}/*"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - index.ts
        External:
          - "@aws-sdk/*"
  
  ApiGatewayEventsFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiGatewayEventsFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PlanningPokerWebsocketApi}/*/*"

  ApiGatewayIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref PlanningPokerWebsocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiGatewayEventsFunction.Arn}/invocations

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PlanningPokerWebsocketApi
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Join ['/', ['integrations', !Ref ApiGatewayIntegration]]

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PlanningPokerWebsocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      Target: !Join ['/', ['integrations', !Ref ApiGatewayIntegration]]

  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref PlanningPokerWebsocketApi
      RouteKey: $default
      AuthorizationType: NONE
      Target: !Join ['/', ['integrations', !Ref ApiGatewayIntegration]]

  DynamoDBEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/dynamoDBEvents/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - execute-api:ManageConnections
            Resource:
              - !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PlanningPokerWebsocketApi}/*"
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PlanningPokerTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
        VoteStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PlanningPokerVote.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - index.ts
        External:
          - "@aws-sdk/*"

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: production
      Description: Prod Stage
      ApiId: !Ref PlanningPokerWebsocketApi
      AutoDeploy: true

Outputs:
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Sub "wss://${PlanningPokerWebsocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"
