AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  planning-poker

  SAM Template for planning-poker API Gateway and Lambdas

Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayEventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/apiGatewayEvents/
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "PlanningPokerTable"
        - DynamoDBCrudPolicy:
            TableName: "PlanningPokerVote"
        - ArnFullAccess:
            Arn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessWebsocketApi}/*"
      Events:
        ConnectEvent:
          Type: Api
          Properties:
            Route: $connect
        DisconnectEvent:
          Type: Api
          Properties:
            Route: $disconnect
        DefaultEvent:
          Type: Api
          Properties:
            Route: $default
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2022"
        Sourcemap: true
        EntryPoints:
          - index.ts

Outputs:
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Sub "wss://${ServerlessWebsocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"
