export const SELECT_CARD = 'SELECT_CARD';
export const REMOVE_CARD = 'REMOVE_CARD';

export const REVEAL_CARDS = 'REVEAL_CARDS';

export const CLIENT_CONNECTED = 'CLIENT_CONNECTED';
export const CLIENT_DISCONNECTED = 'CLIENT_DISCONNECTED';