name: Manual Deploy 'notify-vote-effort' lambda
on: 
   workflow_dispatch
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        working-directory: './infrastructure/lambdas/notify-vote-effort'
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Install Zip
        uses: montudor/action-zip@v1
      - name: Zip output
        working-directory: './infrastructure/lambdas/notify-vote-effort/dist'
        run: zip -qq -r index.zip .
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: notify-vote-effort
          zip_file: ./infrastructure/lambdas/notify-vote-effort/dist/index.zip
